# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-09 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20170708_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='picture',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='website',
            new_name='registration_id',
        ),
    ]
