# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-12 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20170710_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='registration_id',
            new_name='username',
        ),
    ]
